language: node_js
sudo: true
node_js:
  - 7.4.0

before_install:
- nvm install 8

install:
- yarn install

script:
- yarn test:cov

deploy:
  provider: heroku
  api_key:
    secure: "DgEu4Pio/GtbkqRc36vLnf3n4W+4zlCIF3XCv7bnoRUXMhdRb13NCWx7g06CiXtvecwhYTE7KI8RU22leG4pzwoCaIFm3y6Zrk2x77wHZovAaMBjxt84mQrwAfagXRmIZJk8QsKqk6fY7FEKaOjttiCjSm5uM7OKeVfmtTkwyzGFPaavdMRPfMJUu8G0ZtLMNm1CwUk7ZkF0CMeidEdkFQO1yLnlijnXB6KhC3/d6kyQrJNlb6G2347tHI74gcgJszGXEe1iRmmA4RWjXLO7G9sMforI4lzA/9WZUifmDIkeP/xhKz8G+LDszL5wVGO4pFp7r14Eu+BUWoyzp8oe3ou4+SZ2y0IlbkXOOdqbKYy2ncg/atvyap3WkvAF9qPFzyzUfUbQjusD7gSFexjWkE4q8IOxDkhBlbpb4+fDM7EgNmqGlaxmQrXPcfFEyooHtWKt6t/r4W/tw30IdI4zZNXP4JsZ/x/hB+xEpk5Lbmg00OMdYUYWdu9J/8S7ajVu7BhhYQm9Q+WE1viSQuaR0A2Q2okX22xMfUdXhi/peWCEYZEC3VTWzf3yQsajcCtkU0vxiNJPGIlM3JVvFP85tm8SH1n1rHWHTzzKpQNR/cntyRdrRSSb8x5yPUN1nvYnBkYPl0wCgEJMdYjrjbDMxSrfiQcQhE4VZrbrE8xkQrc="
  app: sync-run